export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAIL = "USER_LIST_FAIL"

export const USER_ADD_REQUEST = "USER_ADD_REQUEST"
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS"
export const USER_ADD_FAIL = "USER_ADD_FAIL"

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST"
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS"
export const USER_EDIT_FAIL = "USER_EDIT_FAIL"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAIL = "USER_DELETE_FAIL"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"